### ISSUE TITLE
Feature: Export to nonproprietary format

### ISSUE THREAD

**Issue by sils** [MyCollab/mycollab#11]
You offer data exports as pdf and "excel" only apparently, the latter being xlsx which is a proprietary microsoft format.

Why not offer a really simple CSV that can be reused by others?

**Comment by haiphucnguyen** [comment]
We will support in the next release 5.2.12. Actually, we have support export to CSV in several screens but not for the all screens in the current release.

Hai

**Comment by haiphucnguyen** [comment]
CSV format is supported
