### ISSUE TITLE
Feature: User Interface

### ISSUE THREAD

**Issue by bluefish09** [MyCollab/mycollab#14]
Where are the necessary css files that shall help me change the color of the dashboard or the header?

**Comment by haiphucnguyen** [comment]
It is the file styles.css in the folder mycollab-web/src/main/resources/VAADIN/themes/mycollab_20160531/styles.css

**Comment by bluefish09** [comment]
@haiphucnguyen thnk you but i am changing the .css file , but its not getting reflected in the app

**Comment by haiphucnguyen** [comment]
You should clean the browser cache. Or check whether the IDE copy to the build folder right? Are you running MyCollab in IDE or running MyCollab binary?

**Comment by bluefish09** [comment]
I am not running in the IDE instead i followed these instructions over here https://community.mycollab.com/docs/hosting-mycollab-on-your-own-server/installing-mycollab/
