### ISSUE TITLE
Sending mail always tries to authenticate on SMTP server

### ISSUE THREAD

**Issue by mchubby** [MyCollab/mycollab#15]
Hi,

I haven't looked at the network level, but it seems all outgoing mails are always sent with authentication regardless of whether mail.username is blank.
https://github.com/MyCollab/mycollab/blob/b1da128e8d312f9be7d0489d5c7783bbad196c80/mycollab-services/src/main/java/com/mycollab/module/mail/DefaultMailer.java#L86
EmailConfiguration.getUser() never returns null, AFAICT?

**Steps to repro**
Configure a local open relay SMTP server
Set in conf/mycollab.properties:
```
mail.username=
mail.password=
```
Restart MyCollab, and use the password reset page.

**Expected**
Mail is sent

**Observed**
Mail is rejected with message "javax.mail.AuthenticationFailedException: 535 5.7.8 Error: authentication failed: generic failure" in the stacktrace.

**Comment by haiphucnguyen** [comment]
Thank you for detail report. We just fixed this issue in the latest commit. Now, the email configuration checks username, port and host values
