### ISSUE TITLE
PDF report generation non-ASCII output problem

### ISSUE THREAD

**Issue by mchubby** [MyCollab/mycollab#17]
in **mycollab-reporting/src/main/resources/my_fonts.xml**, pdfEncoding should be Identity-H
(See http://developers.itextpdf.com/tutorial/using-fonts-pdf-and-itext)

Steps to reproduce:
- Print a task, whose name contains non-ASCII characters
- Open PDF in associated viewer

Observed:
- Missing diacritics

**Comment by haiphucnguyen** [comment]
Good catch! We are using dynamic-reports, and we are using the font DejaVuSerif, it is the Western font and the encoding UTF-8 is fine.  Of course, it can not print the PDF to non-ASCII characters without using other fonts. We want to dynamic loading the embedding fonts per chosen locale of users. Hard-coding the font names in the config file is not what we wanted.

We embed the fonts to the non-English users, for example, it is the Japanese font and uses the encoding is Identity-H. However, we do not spend enough effort to flexible support fonts per users' locale even in our cloud product. 

I left this issue and will investigate the solution when we have time.

**Comment by mchubby** [comment]
Actually, when I said non-ASCII, it also includes some very basic characters like éè that are missing.
Here's a list of valid PDF encodings:
https://github.com/robcowell/dynamicreports/blob/master/dynamicreports-core/src/main/java/net/sf/dynamicreports/report/constant/PdfEncoding.java

**Comment by haiphucnguyen** [comment]
Thank you. I forgot to check the pdf encoding values but using the UTF-8 value, it does not work. We changed to the value CP1252 and characters like  éè displays well. The new commit is pushed today and we will include this change in the new build.
