### ISSUE TITLE
Couldn't Build Mycollab master brach

### ISSUE THREAD

**Issue by mygithubwork** [MyCollab/mycollab#23]
I am trying to create mycollab installer, I did the below 
> git clone https://github.com/MyCollab/mycollab.git
>switch to mycollab-app-community 
> mvn install -Dmaven.skip.test=true

I am getting below error message

[ERROR] Failed to execute goal on project mycollab-app-community: Could not reso
lve dependencies for project com.mycollab:mycollab-app-community:jar:5.4.5: The
following artifacts could not be resolved: com.mycollab:mycollab-server-runner:j
ar:5.4.5, com.mycollab:mycollab-servlet:jar:5.4.5, com.mycollab:mycollab-service
s-community:jar:5.4.5, com.mycollab:mycollab-scheduler-community:jar:5.4.5, com.
mycollab:mycollab-mobile:jar:5.4.5, com.mycollab:mycollab-web-community:jar:5.4.
5: Failure to find com.mycollab:mycollab-server-runner:jar:5.4.5 in https://raw.
githubusercontent.com/MyCollab/mycollab-maven-repo/master/ was cached in the loc
al repository, resolution will not be reattempted until the update interval of m
ycollab-repo has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
n project mycollab-app-community: Could not resolve dependencies for project com
.mycollab:mycollab-app-community:jar:5.4.5: The following artifacts could not be
 resolved: com.mycollab:mycollab-server-runner:jar:5.4.5, com.mycollab:mycollab-
servlet:jar:5.4.5, com.mycollab:mycollab-services-community:jar:5.4.5, com.mycol
lab:mycollab-scheduler-community:jar:5.4.5, com.mycollab:mycollab-mobile:jar:5.4
.5, com.mycollab:mycollab-web-community:jar:5.4.5: Failure to find com.mycollab:
mycollab-server-runner:jar:5.4.5 in https://raw.githubusercontent.com/MyCollab/m
ycollab-maven-repo/master/ was cached in the local repository, resolution will n
ot be reattempted until the update interval of mycollab-repo has elapsed or upda
tes are forced

**Comment by quickeee** [comment]
Hi Sorry for reporting above issue.. it was solved when i setup JAVA_HOME to jdk1.8 , but build failed 
with error message, can't copy 
mycollab-app-community\src\main\logs, there is no such folder.

**Comment by haiphucnguyen** [comment]
You can the latest source, we added the log folder to avoid the build issue.
