### ISSUE TITLE
Breaks spring boot embedded tomcat session

### ISSUE THREAD

**Issue by boliakas** [MyCollab/mycollab#27]
Hi,

I have my internal springboot application running on 9095 port in my server. After launching MyCollab on same machine, on 8080 port, my internal application started to kick off (logging out) from it after several second from login action. Could you advise where could be a problem on that? Or maybe there is some more advanced configuration. Thanks

Thanks,

Tomas

**Comment by haiphucnguyen** [comment]
This is the strange issue, and be honest I don't see any source comes from MyCollab or any program. We also use only one port 8080 (or the custom port), and have no specific advance action that runs outside the scope of the JVM. 

Does the server has enough memory for two Java applications? And did you check the log file of the Spring boot application and MyCollab? The log files may tell something to us about what has been happening :)

**Comment by haiphucnguyen** [comment]
Close issue while we don't receive the detail information
