### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by river1995** [MyCollab/mycollab#40]
Hi, I have a question about setting up software, It's always in loading page even one night, the program in IDEA is running well, and no error message in console . And I checked the database connection and SMTP connection is working. But it still can't redirect automatically to the application home page. See pic : 
![image](https://user-images.githubusercontent.com/26372406/49554582-c1847100-f937-11e8-8f15-214d69fc0ffa.png) .
![image](https://user-images.githubusercontent.com/26372406/49554595-c9dcac00-f937-11e8-9b5e-a1e69dac38aa.png)
Thx !

**Comment by river1995** [comment]
Then I finish it by hand and redeploy project, it show me this error :
![image](https://user-images.githubusercontent.com/26372406/49557910-2fcf3080-f944-11e8-8c91-b125a874e960.png)
Waiting for feedbacks, Thank you very much!

**Comment by haiphucnguyen** [comment]
You should run the maven install under the project mycollab-deployer-community, it will deploy all mycollab sub projects and generate the Vaadin stuffs. Then run the application again, it should run well
