### ISSUE TITLE
Can you add "set time zone" in setup tutorial?

### ISSUE THREAD

**Issue by DavidAtWorking** [MyCollab/mycollab#45]
I am using mac OS. While I am installing mycollab. I cannot connect the database and the error says 
`java.sql.SQLException: The server time zone value 'EDT' is unrecognized or represents more than one time zone.
`
During several hours of debug I found that I need to setup timezone in terminal for mysql: `SET GLOBAL time_zone = '-4:00';`
Can you add this to tutorial?

**Comment by haiphucnguyen** [comment]
Thanks for the report! I'd like to fix in the code that let the user don't do anything

We can add it to the application.properties file with the attribute serverTimezone=UTC (Actually, all time values save into the DB are converted to the UTC timezone to make them independently with database or user timezone).

spring.datasource.url=jdbc:mysql://localhost/<DB>?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useCompression=true&useServerPrepStmts=false&verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

I will update the code in the next commit.

Cheers,
Hai Nguyen
