### ISSUE TITLE
Missing : in task link

### ISSUE THREAD

**Issue by AxelTB** [MyCollab/mycollab#8]
I'm pretty new to this software but I noticed a problem that shouldn't be about my configuration.

In the task view the main task link is missing a ":" making the link look like:
```
http//192.168.156.133:8080/#project/task/task/preview/000-3
```

Is there any way to fix it?

**Comment by haiphucnguyen** [comment]
The link of task, or anything to build the hyperlink is based on value of key app.url.

Could you please check your mycollab.properties in %MYCOLLAB_HOME/conf% and tell me what is the value of app.url ?

If you are running MyCollab in IntelliJ, check the config file in the mycollab-app-community/src/main/conf. This issue should not be happened at our end anyway.

Hai

**Comment by haiphucnguyen** [comment]
The value of app.url must be app.url=http://%s:%d/. And we never change it to any value :)

**Comment by AxelTB** [comment]
Unlikely doesn't seem to be that. In my ./conf/mycollab.properties I have:
```
#=====================================================
#    LINK CONFIGURATION
# You should not change these values.
#=====================================================
cdn.url=http://%s:%d/assets/
app.url=http://%s:%d/
resource.downloadUrl=http://%s:%d/file/
```

I've already searched in all the project the string "http//" but doesn't seem to exist...

**Comment by haiphucnguyen** [comment]
Could you check the value server.address, it should be the server name or IP without the value protocol such as http, https. The url is the combination of server.address and server port. MyCollab is installed on various servers of our customers and for sure the string like "http//" never happen.

**Comment by haiphucnguyen** [comment]
Close for low activity and no response
